---
Name: orderadminconfig
---

SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - "silvercommerce/orders-admin: client/dist/js/admin.js"
  extra_requirements_css:
    - "silvercommerce/orders-admin: client/dist/css/admin.css"

## Extensions
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SilverCommerce\OrdersAdmin\Extensions\SiteConfigExtension
SilverStripe\Security\Member:
  extensions:
    - SilverCommerce\OrdersAdmin\Extensions\MemberExtension
SilverStripe\Security\Group:
  extensions:
    - SilverCommerce\OrdersAdmin\Extensions\GroupExtension
SilverCommerce\ContactAdmin\Model\Contact:
  extensions:
    - SilverCommerce\OrdersAdmin\Extensions\ContactExtension