---
Name: orderadminconfig
---
## Extensions
SilverStripe\Admin\LeftAndMain:
  extensions:
    - ilateral\SilverStripe\Orders\Extensions\AdminExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - ilateral\SilverStripe\Orders\Extensions\SiteConfigExtension
SilverStripe\Security\Member:
  extensions:
    - ilateral\SilverStripe\Orders\Extensions\MemberExtension
SilverStripe\Security\Group:
  extensions:
    - ilateral\SilverStripe\Orders\Extensions\GroupExtension
ilateral\SilverStripe\Orders\Model\Order:
  extensions:
    - SilverStripe\Omnipay\Extensions\Payable