---
Name: orderadminconfig
---
## Extensions
SilverStripe\Admin\LeftAndMain:
  extensions:
    - SilverCommerce\OrdersAdmin\Extensions\AdminExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SilverCommerce\OrdersAdmin\Extensions\SiteConfigExtension
SilverStripe\Security\Member:
  extensions:
    - SilverCommerce\OrdersAdmin\Extensions\MemberExtension
SilverStripe\Security\Group:
  extensions:
    - SilverCommerce\OrdersAdmin\Extensions\GroupExtension
SilverCommerce\OrdersAdmin\Model\Order:
  extensions:
    - SilverStripe\Omnipay\Extensions\Payable